CREATE DATABASE MUSIFYDBMSPROJECT;
USE MUSIFY;

CREATE TABLE PLAYLIST(PLAYNO INT PRIMARY KEY,PLAYLISTNAME VARCHAR(20));

CREATE TABLE SONGS(SONGID INT PRIMARY KEY,SONGNAME VARCHAR(20),SONGIMAGE BLOB,AUDIOFILE BLOB);

CREATE TABLE SONGS_SINGER(SONGID INT,SINGERNAME VARCHAR(100),PRIMARY KEY (SONGID,SINGERNAME));

CREATE TABLE APPUSER(USERID INT PRIMARY KEY,PASSWORD VARCHAR(20) UNIQUE,USERNAME VARCHAR(20) NOT NULL,AGE INT CHECK (AGE >= 18),EMAIL VARCHAR(100) NOT NULL,MEMBERSHIP VARCHAR(20),FLAT VARCHAR(100),STREET VARCHAR(100),CITY VARCHAR(20),STATE VARCHAR(20));

CREATE TABLE ALBUM(ALBUMID INT PRIMARY KEY,ALBUMNAME VARCHAR(20) NOT NULL,USERID INT);

ALTER TABLE ALBUM ADD CONSTRAINT USER_FK FOREIGN KEY (USERID) REFERENCES APPUSER(USERID);

CREATE TABLE CONTRIBUTES(ALBUMID INT,USERID INT,PRIMARY KEY(ALBUMID,USERID));

ALTER TABLE CONTRIBUTES ADD CONSTRAINT AUSER_FK FOREIGN KEY (USERID) REFERENCES APPUSER(USERID);

ALTER TABLE CONTRIBUTES ADD CONSTRAINT ALU_FK FOREIGN KEY (USERID) REFERENCES ALBUM(ALBUMID);

ALTER TABLE CONTRIBUTES ADD CONSTRAINT ALBUM_FK FOREIGN KEY (USERID) REFERENCES ALBUM(ALBUMID);

CREATE TABLE FRIEND(USERID INT,FRIEND INT,PRIMARY KEY(USERID,FRIEND));

CREATE TABLE LISTEN(USERID INT,SONGID INT,PRIMARY KEY(USERID,SONGID));

CREATE TABLE CREATEDBY(PLAYNO INT,USERID INT,PRIMARY KEY(USERID,PLAYNO));

CREATE TABLE PARTOF(SONGID INT,ALBUMID INT,PRIMARY KEY(ALBUMID,SONGID));

CREATE TABLE PARTPLAYLIST(SONGID INT,PLAYNO INT,PRIMARY KEY(SONGID,PLAYNO));

ALTER TABLE FRIEND ADD CONSTRAINT FUSER_FK FOREIGN KEY (USERID) REFERENCES APPUSER(USERID);

ALTER TABLE LISTEN ADD CONSTRAINT MUSER_FK FOREIGN KEY (USERID) REFERENCES APPUSER(USERID);

ALTER TABLE CREATEDBY ADD CONSTRAINT CUSER_FK FOREIGN KEY (USERID) REFERENCES APPUSER(USERID);

ALTER TABLE CREATEDBY ADD CONSTRAINT PLAYNO_FK FOREIGN KEY (PLAYNO) REFERENCES PLAYLIST(PLAYNO);

ALTER TABLE PARTOF ADD CONSTRAINT SONG_FK FOREIGN KEY (SONGID) REFERENCES SONGS(SONGID);

ALTER TABLE PARTOF ADD CONSTRAINT ALBUMS_FK FOREIGN KEY (ALBUMID) REFERENCES ALBUM(ALBUMID);

ALTER TABLE PARTPLAYLIST ADD CONSTRAINT S_FK FOREIGN KEY (SONGID) REFERENCES SONGS(SONGID);

ALTER TABLE PARTPLAYLIST ADD CONSTRAINT P_FK FOREIGN KEY (PLAYNO) REFERENCES PLAYLIST(PLAYNO);

CREATE TABLE USER_PHONE(USERID INT,PHONENO INT,PRIMARY KEY(USERID,PHONENO));

ALTER TABLE USER_PHONE ADD CONSTRAINT UPHONE_FK FOREIGN KEY (USERID) REFERENCES APPUSER(USERID);